DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `email` TEXT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS `movies`;
CREATE TABLE `movies` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `title` TEXT NOT NULL,
  `released_at` INTEGER NOT NULL
);

DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `user_id` INTEGER NOT NULL,
  `movie_id` INTEGER NOT NULL,
  UNIQUE(`user_id`, `movie_id`)
);
