CREATE TABLE `users` (
  `id`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `email` TEXT NOT NULL UNIQUE
);

CREATE TABLE `movies` (
  `id`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `title` TEXT NOT NULL,
  `released_at` INTEGER NOT NULL
);

CREATE TABLE `notifications` (
  `id`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `user_id`  INTEGER NOT NULL,
  `movie_id`  INTEGER NOT NULL
);
